import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'

export default withMermaid(defineConfig({
  title: 'LangChain & LangGraph 学习平台',
  description: '从零到精通 LangChain 与 LangGraph 的完整知识体系 · 1518 篇文档 · 28 阶段 155 课系统课程 · 35+ 行业应用',
  lang: 'zh-CN',
  lastUpdated: true,
  cleanUrls: true,

  head: [
    ['meta', { name: 'theme-color', content: '#6366f1' }],
    ['meta', { name: 'author', content: 'AStudio' }],
    ['meta', { property: 'og:title', content: 'LangChain & LangGraph 学习平台' }],
    ['meta', { property: 'og:description', content: '1518 篇文档 · 28 阶段 155 课系统课程 · 35+ 行业应用 · 从零到精通' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
    ['link', { rel: 'apple-touch-icon', href: '/logo.svg' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', {
      href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap',
      rel: 'stylesheet'
    }],
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'LangChain & LangGraph',

    nav: [
      { text: '首页', link: '/' },
      {
        text: '系统课程',
        items: [
          { text: '课程总纲与毕业总结', link: '/课程总纲' },
          { text: '阶段1: LangChain核心架构 (第1-3课)', link: '/系统课程/第01课_大语言模型应用开发入门' },
          { text: '阶段4: 安全防护与部署 (第10-13课)', link: '/系统课程/第10课_从开发到部署_LangChain应用上线实战' },
          { text: '阶段17: MCP协议深入 (第62-65课)', link: '/系统课程/第66课_MCP实战一像点餐一样看懂MCP' },
          { text: '阶段20: LangGraph Platform (第74-77课)', link: '/系统课程/第78课_从本地到云端认识LangGraph Platform' },
          { text: '阶段22: 行业Agent实战 (第82-89课)', link: '/系统课程/第86课_从学完到用起来垂直行业项目入门' },
          { text: '— 快速入门课程 (13课)', link: '/课程/00-课程总览与学习路径' },
        ]
      },
      {
        text: '知识库',
        items: [
          { text: '工程实践 (591篇)', link: '/知识库/01-技术术语表' },
          { text: '技术参考 (109篇)', link: '/技术参考/01_LangChain核心架构技术参考' },
        ]
      },
      { text: '图解', link: '/图解/00-学习路线全景图' },
      { text: '实战案例', link: '/实战案例库/00-案例库导读' },
      { text: '附录速查', link: '/附录/附录A_环境搭建与快速入门指南' },
      { text: '学习评估', link: '/学习评估/01-学习里程碑与进度跟踪' },
      {
        text: '外部链接',
        items: [
          { text: 'LangChain 官方', link: 'https://python.langchain.com' },
          { text: 'LangGraph 官方', link: 'https://langchain-ai.github.io/langgraph' },
          { text: 'GitHub 仓库', link: 'https://github.com/1739467001-svg/Astudio_langchain-langgraph' },
        ]
      },
    ],

    search: {
      provider: 'local',
      options: {
        translations: {
          button: { buttonText: '搜索文档', buttonAriaLabel: '搜索文档' },
          modal: {
            noResultsText: '无法找到相关结果',
            resetButtonTitle: '清除查询条件',
            footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' }
          }
        }
      }
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/1739467001-svg/Astudio_langchain-langgraph' }
    ],

    footer: {
      message: '1518 篇文档 · 155 课系统课程 · 109 篇技术参考 · 52 篇附录 · 35+ 行业应用 · 持续更新中',
      copyright: 'MIT Licensed · Built with VitePress'
    },

    sidebar: {
      '/系统课程/': [
        { text: '阶段1: LangChain核心架构入门', collapsed: false, items: [
          { text: '第01课 - 大语言模型应用开发入门', link: '/系统课程/第01课_大语言模型应用开发入门' },
          { text: '第02课 - LangChain初体验', link: '/系统课程/第02课_LangChain初体验' },
          { text: '第03课 - Prompt工程与模板化设计', link: '/系统课程/第03课_Prompt工程与模板化设计' },
        ]},
        { text: '阶段2: LangGraph与API集成', collapsed: true, items: [
          { text: '第04课 - 记忆机制 让AI记住对话历史', link: '/系统课程/第04课_记忆机制_让AI记住对话历史' },
          { text: '第05课 - 输出解析与结构化数据', link: '/系统课程/第05课_输出解析与结构化数据' },
          { text: '第06课 - 工具与代理Agent 让AI行动起来', link: '/系统课程/第06课_工具与代理Agent_让AI行动起来' },
        ]},
        { text: '阶段3: LCEL表达式与高级RAG', collapsed: true, items: [
          { text: '第07课 - 检索增强生成RAG 让AI拥有知识', link: '/系统课程/第07课_检索增强生成RAG_让AI拥有知识' },
          { text: '第08课 - LangGraph入门 用图思维编排AI', link: '/系统课程/第08课_LangGraph入门_用图思维编排AI' },
          { text: '第09课 - 复杂工作流与多Agent协作', link: '/系统课程/第09课_复杂工作流与多Agent协作' },
        ]},
        { text: '阶段4: 安全防护与生产部署', collapsed: true, items: [
          { text: '第10课 - 从开发到部署 LangChain应用上线实战', link: '/系统课程/第10课_从开发到部署_LangChain应用上线实战' },
          { text: '第11课 - LCEL深入 管道运算符与流式输出', link: '/系统课程/第11课_LCEL深入_管道运算符与流式输出' },
          { text: '第12课 - 高级RAG技术 让检索更精准', link: '/系统课程/第12课_高级RAG技术_让检索更精准' },
          { text: '第13课 - 综合实战 从零构建AI知识助手', link: '/系统课程/第13课_综合实战_从零构建AI知识助手' },
        ]},
        { text: '阶段5: 最佳实践与向量数据库', collapsed: true, items: [
          { text: '第14课 - 多模态AI 处理图片和音频', link: '/系统课程/第14课_多模态AI_处理图片和音频' },
          { text: '第15课 - 安全防护 让AI应用更安全', link: '/系统课程/第15课_安全防护_让AI应用更安全' },
          { text: '第16课 - 生产部署进阶 Docker与监控', link: '/系统课程/第16课_生产部署进阶_Docker与监控' },
          { text: '第17课 - 最佳实践 写出专业级代码', link: '/系统课程/第17课_最佳实践_写出专业级代码' },
        ]},
        { text: '阶段6: 文档解析与流式处理', collapsed: true, items: [
          { text: '第18课 - LangGraph进阶 子图与人在回路', link: '/系统课程/第18课_LangGraph进阶_子图与人在回路' },
          { text: '第19课 - 向量数据库 如何选择适合的向量库', link: '/系统课程/第19课_向量数据库_如何选择适合的向量库' },
          { text: '第20课 - RAG架构模式 从简单到高级', link: '/系统课程/第20课_RAG架构模式_从简单到高级' },
          { text: '第21课 - 数据预处理 让文档变得可搜索', link: '/系统课程/第21课_数据预处理_让文档变得可搜索' },
        ]},
        { text: '阶段7: Agent工具与RAG优化', collapsed: true, items: [
          { text: '第22课 - 结构化输出 让AI说规范的话', link: '/系统课程/第22课_结构化输出_让AI说规范的话' },
          { text: '第23课 - Embedding模型 选择合适的向量表示', link: '/系统课程/第23课_Embedding模型_选择合适的向量表示' },
          { text: '第24课 - 多Agent编排 主管与层级模式', link: '/系统课程/第24课_多Agent编排_主管与层级模式' },
          { text: '第25课 - 流式处理 让AI回复如流水', link: '/系统课程/第25课_流式处理_让AI回复如流水' },
        ]},
        { text: '阶段8: 复杂工作流与自定义模型', collapsed: true, items: [
          { text: '第26课 - Agent工具集成 让AI拥有双手', link: '/系统课程/第26课_Agent工具集成_让AI拥有双手' },
          { text: '第27课 - 记忆系统 让AI拥有持久记忆', link: '/系统课程/第27课_记忆系统_让AI拥有持久记忆' },
          { text: '第28课 - LangGraph状态管理 精确控制AI工作流', link: '/系统课程/第28课_LangGraph状态管理_精确控制AI工作流' },
          { text: '第29课 - 高级RAG优化 让检索更聪明', link: '/系统课程/第29课_高级RAG优化_让检索更聪明' },
        ]},
        { text: '阶段9: GraphRAG与代码Agent', collapsed: true, items: [
          { text: '第30课 - LangGraph复杂工作流 高级图模式', link: '/系统课程/第30课_LangGraph复杂工作流_高级图模式' },
          { text: '第31课 - Agent评估 让AI越来越准', link: '/系统课程/第31课_Agent评估_让AI越来越准' },
          { text: '第32课 - 生产级RAG调优 让检索更专业', link: '/系统课程/第32课_生产级RAG调优_让检索更专业' },
          { text: '第33课 - 自定义模型集成 接入你自己的模型', link: '/系统课程/第33课_自定义模型集成_接入你自己的模型' },
        ]},
        { text: '阶段10: Agent安全与幻觉检测', collapsed: true, items: [
          { text: '第34课 - GraphRAG 让检索长出一张知识网', link: '/系统课程/第34课_GraphRAG_让检索长出一张知识网' },
          { text: '第35课 - 代码Agent 教AI写代码跑代码改代码', link: '/系统课程/第35课_代码Agent_教AI写代码跑代码改代码' },
          { text: '第36课 - LangGraph调试 给AI应用装一个时间机器', link: '/系统课程/第36课_LangGraph调试_给AI应用装一个时间机器' },
          { text: '第37课 - AgenticRAG 让检索自己动脑子', link: '/系统课程/第37课_AgenticRAG_让检索自己动脑子' },
        ]},
        { text: '阶段11: 推理优化与多模态Agent', collapsed: true, items: [
          { text: '第38课 - Agent安全 给你的AI应用上把锁', link: '/系统课程/第38课_Agent安全_给你的AI应用上把锁' },
          { text: '第39课 - LLM网关 多模型统一调度入门', link: '/系统课程/第39课_LLM网关_多模型统一调度入门' },
          { text: '第40课 - 上下文工程 把最贵的记忆管好', link: '/系统课程/第40课_上下文工程_把最贵的记忆管好' },
          { text: '第41课 - 幻觉检测 让AI学会说实话', link: '/系统课程/第41课_幻觉检测_让AI学会说实话' },
        ]},
        { text: '阶段12: 合规治理与多智能体框架', collapsed: true, items: [
          { text: '第42课 - 性能优化 让AI应用跑得更快更省', link: '/系统课程/第42课_性能优化_让AI应用跑得更快更省' },
          { text: '第43课 - 微调与RAG 查字典还是上培训班', link: '/系统课程/第43课_微调与RAG_查字典还是上培训班' },
          { text: '第44课 - 多模态Agent 让AI看懂世界', link: '/系统课程/第44课_多模态Agent_让AI看懂世界' },
          { text: '第45课 - 毕业实战 从0到1的完整项目', link: '/系统课程/第45课_毕业实战_从0到1的完整项目' },
        ]},
        { text: '阶段13: 新特性与MCP生态', collapsed: true, items: [
          { text: '第46课 - RAG评测 给AI打分', link: '/系统课程/第46课_RAG评测_给AI打分' },
          { text: '第47课 - 云平台部署 把项目搬上云', link: '/系统课程/第47课_云平台部署_把项目搬上云' },
          { text: '第48课 - 多智能体框架 指挥团队怎么选', link: '/系统课程/第48课_多智能体框架_指挥团队怎么选' },
          { text: '第49课 - Agent架构模式 7种模式一次看懂', link: '/系统课程/第49课_Agent架构模式_7种模式一次看懂' },
        ]},
        { text: '阶段14: 多租户架构与隔离', collapsed: true, items: [
          { text: '第50课 - 新特性追踪 跟上框架的脚步', link: '/系统课程/第50课_新特性追踪_跟上框架的脚步' },
          { text: '第51课 - Runtime新写法 一行看懂Context', link: '/系统课程/第51课_Runtime新写法_一行看懂Context' },
          { text: '第52课 - 平滑升级 老代码迁移指南', link: '/系统课程/第52课_平滑升级_老代码迁移指南' },
          { text: '第53课 - 收官展望 未来学习路线图', link: '/系统课程/第53课_收官展望_未来学习路线图' },
        ]},
        { text: '阶段15: 企业知识库端到端实战', collapsed: true, items: [
          { text: '第54课 - 多租户入门 一个平台服务许多客户', link: '/系统课程/第54课_多租户入门_一个平台服务许多客户' },
          { text: '第55课 - 租户隔离 数据不能串门', link: '/系统课程/第55课_租户隔离_数据不能串门' },
          { text: '第56课 - 成本配额 钱要算得明白', link: '/系统课程/第56课_成本配额_钱要算得明白' },
          { text: '第57课 - 平台运营 从单应用走向企业平台', link: '/系统课程/第57课_平台运营_从单应用走向企业平台' },
        ]},
        { text: '阶段16: 可观测性与安全治理', collapsed: true, items: [
          { text: '第58课 - 综合实战一 像搭积木一样设计企业知识库', link: '/系统课程/第58课_综合实战一_像搭积木一样设计企业知识库' },
          { text: '第59课 - 综合实战二 把一堆文档变成知识', link: '/系统课程/第59课_综合实战二_把一堆文档变成知识' },
          { text: '第60课 - 综合实战三 建评测集把感觉还行变成数据说话', link: '/系统课程/第60课_综合实战三_建评测集把感觉还行变成数据说话' },
          { text: '第61课 - 综合实战四 上线迭代以及你的下一步', link: '/系统课程/第61课_综合实战四_上线迭代以及你的下一步' },
        ]},
        { text: '阶段17: MCP协议深入实战', collapsed: true, items: [
          { text: '第62课 - 生产可观测性入门给系统装上仪表盘', link: '/系统课程/第62课_生产可观测性入门给系统装上仪表盘' },
          { text: '第63课 - 评测自动化入门让质量变成一道门禁', link: '/系统课程/第63课_评测自动化入门让质量变成一道门禁' },
          { text: '第64课 - 可靠性工程入门给过山车装保险丝', link: '/系统课程/第64课_可靠性工程入门给过山车装保险丝' },
          { text: '第65课 - 收官安全成本双体检与你的进阶路线', link: '/系统课程/第65课_收官安全成本双体检与你的进阶路线' },
        ]},
        { text: '阶段18: Agent评测体系', collapsed: true, items: [
          { text: '第66课 - MCP实战一像点餐一样看懂MCP', link: '/系统课程/第66课_MCP实战一像点餐一样看懂MCP' },
          { text: '第67课 - MCP实战二手写你的第一个MCP服务', link: '/系统课程/第67课_MCP实战二手写你的第一个MCP服务' },
          { text: '第68课 - MCP实战三把MCP服务装进你的Agent', link: '/系统课程/第68课_MCP实战三把MCP服务装进你的Agent' },
          { text: '第69课 - MCP实战四让MCP服务安全上线收官', link: '/系统课程/第69课_MCP实战四让MCP服务安全上线收官' },
        ]},
        { text: '阶段19: Human-in-the-Loop', collapsed: true, items: [
          { text: '第70课 - AI的考试卷认识Agent评测', link: '/系统课程/第70课_AI的考试卷认识Agent评测' },
          { text: '第71课 - 亲手跑一个τ-bench用例你的Agent第一次上考场', link: '/系统课程/第71课_亲手跑一个τ-bench用例你的Agent第一次上考场' },
          { text: '第72课 - 造你自己的考卷评测集与LLM-Judge', link: '/系统课程/第72课_造你自己的考卷评测集与LLM-Judge' },
          { text: '第73课 - 让评测拦住烂版本EDD与CI门禁收官', link: '/系统课程/第73课_让评测拦住烂版本EDD与CI门禁收官' },
        ]},
        { text: '阶段20: LangGraph Platform与部署', collapsed: true, items: [
          { text: '第74课 - 什么时候该让人参与认识Human-in-the-Loop', link: '/系统课程/第74课_什么时候该让人参与认识Human-in-the-Loop' },
          { text: '第75课 - 给Agent装上刹车中断与恢复', link: '/系统课程/第75课_给Agent装上刹车中断与恢复' },
          { text: '第76课 - 人机接力赛纠错与回退', link: '/系统课程/第76课_人机接力赛纠错与回退' },
          { text: '第77课 - 让人在回路里不添乱HITL落地与全系列收官', link: '/系统课程/第77课_让人在回路里不添乱HITL落地与全系列收官' },
        ]},
        { text: '阶段21: LangSmith深度解析', collapsed: true, items: [
          { text: '第78课 - 从本地到云端认识LangGraph Platform', link: '/系统课程/第78课_从本地到云端认识LangGraph Platform' },
          { text: '第79课 - 把你的Agent部署到生产持久化配置与上线全流程', link: '/系统课程/第79课_把你的Agent部署到生产持久化配置与上线全流程' },
          { text: '第80课 - 让Agent自己定时干活Cron定时任务与后台异步任务', link: '/系统课程/第80课_让Agent自己定时干活Cron定时任务与后台异步任务' },
          { text: '第81课 - 看见你的Agent在想什么Studio可视化调试与全系列收官', link: '/系统课程/第81课_看见你的Agent在想什么Studio可视化调试与全系列收官' },
        ]},
        { text: '阶段22: 垂直行业Agent实战', collapsed: true, items: [
          { text: '第82课 - 认识LangSmith从追踪到可观测性', link: '/系统课程/第82课_认识LangSmith从追踪到可观测性' },
          { text: '第83课 - 用Trace找Bug追踪系统实战', link: '/系统课程/第83课_用Trace找Bug追踪系统实战' },
          { text: '第84课 - 用数据集做实验AB对比与回归测试', link: '/系统课程/第84课_用数据集做实验AB对比与回归测试' },
          { text: '第85课 - LangSmith全景回顾与全系列总收官', link: '/系统课程/第85课_LangSmith全景回顾与全系列总收官' },
          { text: '第86课 - 从学完到用起来垂直行业项目入门', link: '/系统课程/第86课_从学完到用起来垂直行业项目入门' },
          { text: '第87课 - 客服Agent从需求到上线全流程', link: '/系统课程/第87课_客服Agent从需求到上线全流程' },
          { text: '第88课 - 法律与金融行业RAG差异化与合规要点', link: '/系统课程/第88课_法律与金融行业RAG差异化与合规要点' },
          { text: '第89课 - 电商医疗Agent实战与全阶段收官', link: '/系统课程/第89课_电商医疗Agent实战与全阶段收官' },
        ]},
        { text: '阶段23-24: 设计模式与论文安全', collapsed: true, items: [
          { text: '第99课 - Agent设计模式入门与ReAct实战', link: '/系统课程/第99课_Agent设计模式入门与ReAct实战' },
          { text: '第100课 - Plan-and-Execute与Reflection实战', link: '/系统课程/第100课_Plan-and-Execute与Reflection实战' },
          { text: '第101课 - Multi-Agent协作模式实战', link: '/系统课程/第101课_Multi-Agent协作模式实战' },
          { text: '第102课 - 设计模式选型与全阶段收官', link: '/系统课程/第102课_设计模式选型与全阶段收官' },
          { text: '第103课 - 论文精读入门与ReAct论文复现实战', link: '/系统课程/第103课_论文精读入门与ReAct论文复现实战' },
          { text: '第104课 - Reflexion与TreeofThoughts复现实战', link: '/系统课程/第104课_Reflexion与TreeofThoughts复现实战' },
          { text: '第105课 - Self-RAG与CRAG复现实战', link: '/系统课程/第105课_Self-RAG与CRAG复现实战' },
          { text: '第106课 - 前沿论文追踪方法与全阶段收官', link: '/系统课程/第106课_前沿论文追踪方法与全阶段收官' },
          { text: '第107课 - LLM安全入门与PromptInjection攻防实战', link: '/系统课程/第107课_LLM安全入门与PromptInjection攻防实战' },
          { text: '第108课 - 越狱攻击防御与安全护栏构建实战', link: '/系统课程/第108课_越狱攻击防御与安全护栏构建实战' },
          { text: '第109课 - OwaspLLMTop10与系统化安全评估实战', link: '/系统课程/第109课_OwaspLLMTop10与系统化安全评估实战' },
          { text: '第110课 - 红队测试实战与全阶段收官', link: '/系统课程/第110课_红队测试实战与全阶段收官' },
        ]},
        { text: '阶段25: 多模态Agent与跨模态检索', collapsed: true, items: [
          { text: '第111课 - 多模态LLM入门与视觉问答实战', link: '/系统课程/第111课_多模态LLM入门与视觉问答实战' },
          { text: '第112课 - 图文混排处理与视觉文档解析实战', link: '/系统课程/第112课_图文混排处理与视觉文档解析实战' },
          { text: '第113课 - 多模态RAG与跨模态检索实战', link: '/系统课程/第113课_多模态RAG与跨模态检索实战' },
          { text: '第114课 - 语音集成与多模态Agent实战全阶段收官', link: '/系统课程/第114课_语音集成与多模态Agent实战全阶段收官' },
        ]},
        { text: '阶段27: 高级编排与多Agent系统', collapsed: true, items: [
          { text: '第123课 - LangGraph高级编排模式入门实战', link: '/系统课程/第123课_LangGraph高级编排模式入门实战' },
          { text: '第124课 - Human-in-the-loop人工介入实战', link: '/系统课程/第124课_Human-in-the-loop人工介入实战' },
          { text: '第125课 - Agent批处理与异步编排实战', link: '/系统课程/第125课_Agent批处理与异步编排实战' },
          { text: '第126课 - Agent产品化与工程化最佳实践', link: '/系统课程/第126课_Agent产品化与工程化最佳实践' },
          { text: '第127课 - 多Agent系统入门从单兵到团队', link: '/系统课程/第127课_多Agent系统入门从单兵到团队' },
          { text: '第128课 - Supervisor与Swarm编排模式实战', link: '/系统课程/第128课_Supervisor与Swarm编排模式实战' },
          { text: '第129课 - 分布式Agent部署入门实战', link: '/系统课程/第129课_分布式Agent部署入门实战' },
          { text: '第130课 - 多Agent协作综合实战与最佳实践', link: '/系统课程/第130课_多Agent协作综合实战与最佳实践' },
        ]},
      ],

      '/技术参考/': [
        { text: '核心参考 (01-09)', collapsed: false, items: [
          { text: '01 - LangChain核心架构技术参考', link: '/技术参考/01_LangChain核心架构技术参考' },
          { text: '02 - LangChain组件详解技术手册', link: '/技术参考/02_LangChain组件详解技术手册' },
          { text: '03 - 数据连接与RAG技术手册', link: '/技术参考/03_数据连接与RAG技术手册' },
          { text: '04 - LangGraph技术参考', link: '/技术参考/04_LangGraph技术参考' },
          { text: '05 - API集成与部署技术参考', link: '/技术参考/05_API集成与部署技术参考' },
          { text: '06 - 生态对比与模型集成数据表', link: '/技术参考/06_生态对比与模型集成数据表' },
          { text: '07 - LCEL表达式语言深入技术参考', link: '/技术参考/07_LCEL表达式语言深入技术参考' },
          { text: '08 - 高级RAG与检索策略技术手册', link: '/技术参考/08_高级RAG与检索策略技术手册' },
          { text: '09 - 评估测试与成本优化技术参考', link: '/技术参考/09_评估测试与成本优化技术参考' },
        ]},
        { text: '生产与安全 (10-13)', collapsed: true, items: [
          { text: '10 - 安全防护与内容审核技术参考', link: '/技术参考/10_安全防护与内容审核技术参考' },
          { text: '11 - 多模态与高级模型集成技术手册', link: '/技术参考/11_多模态与高级模型集成技术手册' },
          { text: '12 - 生产部署模式与可观测性技术参考', link: '/技术参考/12_生产部署模式与可观测性技术参考' },
          { text: '13 - 最佳实践与反模式手册', link: '/技术参考/13_最佳实践与反模式手册' },
        ]},
        { text: '向量库与RAG (14-17)', collapsed: true, items: [
          { text: '14 - LangGraph高级模式技术手册', link: '/技术参考/14_LangGraph高级模式技术手册' },
          { text: '15 - 向量数据库选型与对比技术参考', link: '/技术参考/15_向量数据库选型与对比技术参考' },
          { text: '16 - RAG架构模式技术手册', link: '/技术参考/16_RAG架构模式技术手册' },
          { text: '17 - 文档解析与数据预处理技术参考', link: '/技术参考/17_文档解析与数据预处理技术参考' },
        ]},
        { text: '文档与流式 (18-21)', collapsed: true, items: [
          { text: '18 - 结构化输出与函数调用技术手册', link: '/技术参考/18_结构化输出与函数调用技术手册' },
          { text: '19 - Embedding模型与策略技术参考', link: '/技术参考/19_Embedding模型与策略技术参考' },
          { text: '20 - 多Agent编排模式技术手册', link: '/技术参考/20_多Agent编排模式技术手册' },
          { text: '21 - 流式处理与异步编程技术参考', link: '/技术参考/21_流式处理与异步编程技术参考' },
        ]},
        { text: 'Agent与RAG优化 (22-25)', collapsed: true, items: [
          { text: '22 - Agent工具集成与自定义工具开发技术手册', link: '/技术参考/22_Agent工具集成与自定义工具开发技术手册' },
          { text: '23 - 记忆系统架构与策略技术参考', link: '/技术参考/23_记忆系统架构与策略技术参考' },
          { text: '24 - LangGraph状态管理与检查点技术手册', link: '/技术参考/24_LangGraph状态管理与检查点技术手册' },
          { text: '25 - 高级RAG优化 重排与查询变换技术参考', link: '/技术参考/25_高级RAG优化_重排与查询变换技术参考' },
        ]},
        { text: '工作流与模型 (26-29)', collapsed: true, items: [
          { text: '26 - LangGraph复杂工作流模式技术手册', link: '/技术参考/26_LangGraph复杂工作流模式技术手册' },
          { text: '27 - Agent评估与测试框架技术参考', link: '/技术参考/27_Agent评估与测试框架技术参考' },
          { text: '28 - 生产级RAG系统调优技术参考', link: '/技术参考/28_生产级RAG系统调优技术参考' },
          { text: '29 - 自定义模型集成与路由技术手册', link: '/技术参考/29_自定义模型集成与路由技术手册' },
        ]},
        { text: 'GraphRAG与调试 (30-33)', collapsed: true, items: [
          { text: '30 - GraphRAG知识图谱增强检索技术手册', link: '/技术参考/30_GraphRAG知识图谱增强检索技术手册' },
          { text: '31 - 代码Agent开发技术手册', link: '/技术参考/31_代码Agent开发技术手册' },
          { text: '32 - 时间旅行与LangGraph调试技术手册', link: '/技术参考/32_时间旅行与LangGraph调试技术手册' },
          { text: '33 - AgenticRAG自主检索技术手册', link: '/技术参考/33_AgenticRAG自主检索技术手册' },
        ]},
        { text: '安全与上下文 (34-37)', collapsed: true, items: [
          { text: '34 - Agent安全纵深防御技术手册', link: '/技术参考/34_Agent安全纵深防御技术手册' },
          { text: '35 - 多租户LLM网关与统一接入架构手册', link: '/技术参考/35_多租户LLM网关与统一接入架构手册' },
          { text: '36 - 上下文工程与长上下文优化技术手册', link: '/技术参考/36_上下文工程与长上下文优化技术手册' },
          { text: '37 - 幻觉检测与可靠性工程技术手册', link: '/技术参考/37_幻觉检测与可靠性工程技术手册' },
        ]},
        { text: '优化与合规 (38-41)', collapsed: true, items: [
          { text: '38 - 推理性能优化与延迟工程技术手册', link: '/技术参考/38_推理性能优化与延迟工程技术手册' },
          { text: '39 - 微调与RAG协同架构技术手册', link: '/技术参考/39_微调与RAG协同架构技术手册' },
          { text: '40 - 多模态Agent与多模态RAG技术手册', link: '/技术参考/40_多模态Agent与多模态RAG技术手册' },
          { text: '41 - LLM应用合规隐私与治理技术手册', link: '/技术参考/41_LLM应用合规隐私与治理技术手册' },
        ]},
        { text: '评测与平台 (42-45)', collapsed: true, items: [
          { text: '42 - RAG评测体系与RAGAS实操技术手册', link: '/技术参考/42_RAG评测体系与RAGAS实操技术手册' },
          { text: '43 - LangGraph云平台与团队协作部署技术手册', link: '/技术参考/43_LangGraph云平台与团队协作部署技术手册' },
          { text: '44 - 多智能体编排框架对比与选型技术手册', link: '/技术参考/44_多智能体编排框架对比与选型技术手册' },
          { text: '45 - Agent架构模式大全技术手册', link: '/技术参考/45_Agent架构模式大全技术手册' },
        ]},
        { text: '新特性与MCP (46-49)', collapsed: true, items: [
          { text: '46 - LangChain新特性全景追踪技术手册', link: '/技术参考/46_LangChain新特性全景追踪技术手册' },
          { text: '47 - LangGraph新版Runtime上下文技术手册', link: '/技术参考/47_LangGraph新版Runtime上下文技术手册' },
          { text: '48 - LangGraph平台与CLI技术手册', link: '/技术参考/48_LangGraph平台与CLI技术手册' },
          { text: '49 - MCP协议与新特性生态整合技术手册', link: '/技术参考/49_MCP协议与新特性生态整合技术手册' },
        ]},
        { text: '多租户与治理 (50-53)', collapsed: true, items: [
          { text: '50 - 多租户架构与隔离策略技术手册', link: '/技术参考/50_多租户架构与隔离策略技术手册' },
          { text: '51 - 租户级数据隔离与检索安全技术手册', link: '/技术参考/51_租户级数据隔离与检索安全技术手册' },
          { text: '52 - 成本计量配额与用量治理技术手册', link: '/技术参考/52_成本计量配额与用量治理技术手册' },
          { text: '53 - 企业级LLM平台合规运营技术手册', link: '/技术参考/53_企业级LLM平台合规运营技术手册' },
        ]},
        { text: '企业实战 (54-61)', collapsed: true, items: [
          { text: '54 - 端到端实战从零搭建企业知识库问答系统', link: '/技术参考/54_端到端实战从零搭建企业知识库问答系统' },
          { text: '55 - 企业知识库的文档治理与数据管线实战', link: '/技术参考/55_企业知识库的文档治理与数据管线实战' },
          { text: '56 - 检索问答链路实战与质量评测', link: '/技术参考/56_检索问答链路实战与质量评测' },
          { text: '57 - 系统部署运营与持续迭代实战', link: '/技术参考/57_系统部署运营与持续迭代实战' },
          { text: '58 - 生产可观测性实战日志指标与追踪', link: '/技术参考/58_生产可观测性实战日志指标与追踪' },
          { text: '59 - 评测自动化与CICD门禁实战', link: '/技术参考/59_评测自动化与CICD门禁实战' },
          { text: '60 - 可靠性工程实战SLO熔断与故障演练', link: '/技术参考/60_可靠性工程实战SLO熔断与故障演练' },
          { text: '61 - 生产安全与成本治理实战', link: '/技术参考/61_生产安全与成本治理实战' },
        ]},
        { text: 'MCP深入 (62-65)', collapsed: true, items: [
          { text: '62 - MCP协议深入消息握手与工具发现机制', link: '/技术参考/62_MCP协议深入消息握手与工具发现机制' },
          { text: '63 - MCP服务端开发实战PythonSDK自建工具服务', link: '/技术参考/63_MCP服务端开发实战PythonSDK自建工具服务' },
          { text: '64 - MCP客户端集成实战LangChainLangGraph接入MCP', link: '/技术参考/64_MCP客户端集成实战LangChainLangGraph接入MCP' },
          { text: '65 - MCP生态与生产实践鉴权安全与部署', link: '/技术参考/65_MCP生态与生产实践鉴权安全与部署' },
        ]},
        { text: '评测体系 (66-69)', collapsed: true, items: [
          { text: '66 - Agent评测全景金字塔四类基准与核心指标', link: '/技术参考/66_Agent评测全景金字塔四类基准与核心指标' },
          { text: '67 - tau-bench工具调用评测实战数据运行与两阶段评分', link: '/技术参考/67_τ-bench工具调用评测实战数据运行与两阶段评分' },
          { text: '68 - 自建Agent评测台评测集LLM-as-Judge与运行报告', link: '/技术参考/68_自建Agent评测台评测集LLM-as-Judge与运行报告' },
          { text: '69 - 评测驱动开发EDD与CI门禁让评测拦住烂版本', link: '/技术参考/69_评测驱动开发EDD与CI门禁让评测拦住烂版本' },
        ]},
        { text: 'HITL (70-73)', collapsed: true, items: [
          { text: '70 - Human-in-the-Loop概念全景与LangGraph中断恢复机制', link: '/技术参考/70_Human-in-the-Loop概念全景与LangGraph中断恢复机制' },
          { text: '71 - 工具调用前人工确认与审批节点设计', link: '/技术参考/71_工具调用前人工确认与审批节点设计' },
          { text: '72 - 纠错回退与多轮人机协同', link: '/技术参考/72_纠错回退与多轮人机协同' },
          { text: '73 - HITL生产落地反模式与质量护栏协同', link: '/技术参考/73_HITL生产落地反模式与质量护栏协同' },
        ]},
        { text: 'Platform与部署 (74-77)', collapsed: true, items: [
          { text: '74 - LangGraph Platform架构全景与三种部署模式', link: '/技术参考/74_LangGraph Platform架构全景与三种部署模式' },
          { text: '75 - 持久化后端与检查点存储实战', link: '/技术参考/75_持久化后端与检查点存储实战' },
          { text: '76 - Cron定时任务与后台异步任务实战', link: '/技术参考/76_Cron定时任务与后台异步任务实战' },
          { text: '77 - Stream Hub实时流式与LangGraph Studio可视化调试', link: '/技术参考/77_Stream Hub实时流式与LangGraph Studio可视化调试' },
        ]},
        { text: 'LangSmith (78-81)', collapsed: true, items: [
          { text: '78 - LangSmith追踪系统深度解析', link: '/技术参考/78_LangSmith追踪系统深度解析' },
          { text: '79 - 数据集管理与实验对比', link: '/技术参考/79_数据集管理与实验对比' },
          { text: '80 - LangSmith Playground与提示词实验', link: '/技术参考/80_LangSmith Playground与提示词实验' },
          { text: '81 - LangSmith可观测性仪表盘与告警', link: '/技术参考/81_LangSmith可观测性仪表盘与告警' },
        ]},
        { text: '行业Agent (82-85)', collapsed: true, items: [
          { text: '82 - 客服Agent端到端项目实战', link: '/技术参考/82_客服Agent端到端项目实战' },
          { text: '83 - 法律金融行业RAG系统实战', link: '/技术参考/83_法律金融行业RAG系统实战' },
          { text: '84 - 电商购物Agent全流程实战', link: '/技术参考/84_电商购物Agent全流程实战' },
          { text: '85 - 医疗问答Agent安全合规实战', link: '/技术参考/85_医疗问答Agent安全合规实战' },
        ]},
        { text: '设计模式 (86-89)', collapsed: true, items: [
          { text: '86 - ReAct推理行动模式深度解析', link: '/技术参考/86_ReAct推理行动模式深度解析' },
          { text: '87 - Plan-and-Execute规划执行模式', link: '/技术参考/87_Plan-and-Execute规划执行模式' },
          { text: '88 - Reflection自省纠错模式', link: '/技术参考/88_Reflection自省纠错模式' },
          { text: '89 - Multi-Agent协作模式大全', link: '/技术参考/89_Multi-Agent协作模式大全' },
        ]},
        { text: '论文与安全 (90-97)', collapsed: true, items: [
          { text: '90 - ReAct论文精读与代码复现', link: '/技术参考/90_ReAct论文精读与代码复现' },
          { text: '91 - Reflexion论文精读与代码复现', link: '/技术参考/91_Reflexion论文精读与代码复现' },
          { text: '92 - TreeofThoughts论文精读与代码复现', link: '/技术参考/92_TreeofThoughts论文精读与代码复现' },
          { text: '93 - Self-RAG与CRAG论文精读与代码复现', link: '/技术参考/93_Self-RAG与CRAG论文精读与代码复现' },
          { text: '94 - PromptInjection攻击原理与防御实战', link: '/技术参考/94_PromptInjection攻击原理与防御实战' },
          { text: '95 - 越狱攻击技术与安全护栏构建', link: '/技术参考/95_越狱攻击技术与安全护栏构建' },
          { text: '96 - OwaspLLMTop10与系统化安全评估', link: '/技术参考/96_OwaspLLMTop10与系统化安全评估' },
          { text: '97 - 红队测试方法论与自动化安全测试', link: '/技术参考/97_红队测试方法论与自动化安全测试' },
        ]},
        { text: '多模态 (98-101)', collapsed: true, items: [
          { text: '98 - 多模态LLM基础架构与视觉问答', link: '/技术参考/98_多模态LLM基础架构与视觉问答' },
          { text: '99 - 图文混排处理与视觉文档解析', link: '/技术参考/99_图文混排处理与视觉文档解析' },
          { text: '100 - 多模态RAG与跨模态检索引擎', link: '/技术参考/100_多模态RAG与跨模态检索引擎' },
          { text: '101 - 语音ASR-TTS集成与多模态Agent', link: '/技术参考/101_语音ASR-TTS集成与多模态Agent' },
        ]},
        { text: '高级编排 (110-117)', collapsed: true, items: [
          { text: '110 - LangGraph高级编排模式与复杂状态机', link: '/技术参考/110_LangGraph高级编排模式与复杂状态机' },
          { text: '111 - Human-in-the-loop人工介入与审批工作流', link: '/技术参考/111_Human-in-the-loop人工介入与审批工作流' },
          { text: '112 - Agent批处理与异步任务编排', link: '/技术参考/112_Agent批处理与异步任务编排' },
          { text: '113 - Agent产品化与工程化最佳实践', link: '/技术参考/113_Agent产品化与工程化最佳实践' },
          { text: '114 - 多Agent系统架构原理与通信协议', link: '/技术参考/114_多Agent系统架构原理与通信协议' },
          { text: '115 - LangGraph多Agent编排模式深度解析', link: '/技术参考/115_LangGraph多Agent编排模式深度解析' },
          { text: '116 - 分布式Agent部署与远程通信', link: '/技术参考/116_分布式Agent部署与远程通信' },
          { text: '117 - 多Agent协作综合应用与最佳实践', link: '/技术参考/117_多Agent协作综合应用与最佳实践' },
        ]},
      ],

      '/附录/': [
        { text: '基础工具 (A-B)', collapsed: false, items: [
          { text: 'A - 环境搭建与快速入门指南', link: '/附录/附录A_环境搭建与快速入门指南' },
          { text: 'B - 术语表与API速查卡', link: '/附录/附录B_术语表与API速查卡' },
        ]},
        { text: '开发与部署 (C-N)', collapsed: true, items: [
          { text: 'C - 常见错误与故障排除速查手册', link: '/附录/附录C_常见错误与故障排除速查手册' },
          { text: 'D - 实战项目模板代码集', link: '/附录/附录D_实战项目模板代码集' },
          { text: 'E - 端到端项目实战 企业知识库问答系统', link: '/附录/附录E_端到端项目实战_企业知识库问答系统' },
          { text: 'F - LangChain生态地图与集成指南', link: '/附录/附录F_LangChain生态地图与集成指南' },
          { text: 'G - Prompt工程工具箱 模板与模式', link: '/附录/附录G_Prompt工程工具箱_模板与模式' },
          { text: 'H - LangSmith与可观测性深度指南', link: '/附录/附录H_LangSmith与可观测性深度指南' },
          { text: 'I - LangChain Callbacks与事件系统指南', link: '/附录/附录I_LangChain_Callbacks与事件系统指南' },
          { text: 'J - LangChain版本迁移与升级指南', link: '/附录/附录J_LangChain版本迁移与升级指南' },
          { text: 'K - LangServe与API服务部署指南', link: '/附录/附录K_LangServe与API服务部署指南' },
          { text: 'L - LangChain测试策略与最佳实践', link: '/附录/附录L_LangChain测试策略与最佳实践' },
          { text: 'M - 前端集成指南', link: '/附录/附录M_前端集成指南' },
          { text: 'N - 数据库Agent与Text-to-SQL深入指南', link: '/附录/附录N_数据库Agent与Text-to-SQL深入指南' },
        ]},
        { text: '生产运维 (O-R)', collapsed: true, items: [
          { text: 'O - 生产监控与告警体系指南', link: '/附录/附录O_生产监控与告警体系指南' },
          { text: 'P - 企业知识库建设与治理指南', link: '/附录/附录P_企业知识库建设与治理指南' },
          { text: 'Q - 生产上线检查清单', link: '/附录/附录Q_生产上线检查清单' },
          { text: 'R - 进阶学习路线与资源导航', link: '/附录/附录R_进阶学习路线与资源导航' },
        ]},
        { text: '故障与升级 (S-V)', collapsed: true, items: [
          { text: 'S - RAG故障诊断速查手册', link: '/附录/附录S_RAG故障诊断速查手册' },
          { text: 'T - LLM应用架构蓝图与组件速查', link: '/附录/附录T_LLM应用架构蓝图与组件速查' },
          { text: 'U - 版本升级迁移速查手册', link: '/附录/附录U_版本升级迁移速查手册' },
          { text: 'V - 新特性更新日志导读与生态导航', link: '/附录/附录V_新特性更新日志导读与生态导航' },
        ]},
        { text: '架构与路线 (W-Z)', collapsed: true, items: [
          { text: 'W - 多租户架构选型速查手册', link: '/附录/附录W_多租户架构选型速查手册' },
          { text: 'X - 租户运营指标与SLA速查', link: '/附录/附录X_租户运营指标与SLA速查' },
          { text: 'Y - 端到端实战速查卡命令配置与检查清单', link: '/附录/附录Y_端到端实战速查卡命令配置与检查清单' },
          { text: 'Z - 全系列知识地图与自测题', link: '/附录/附录Z_全系列知识地图与自测题' },
        ]},
        { text: '速查手册 AA-AF', collapsed: true, items: [
          { text: 'AA - 生产运行命令速查与检查清单', link: '/附录/附录AA_生产运行命令速查与检查清单' },
          { text: 'AB - 故障演练剧本与复盘模板', link: '/附录/附录AB_故障演练剧本与复盘模板' },
          { text: 'AC - MCP消息格式与命令速查手册', link: '/附录/附录AC_MCP消息格式与命令速查手册' },
          { text: 'AD - MCP服务部署与安全检查清单', link: '/附录/附录AD_MCP服务部署与安全检查清单' },
          { text: 'AE - Agent评测基准速查手册', link: '/附录/附录AE_Agent评测基准速查手册' },
          { text: 'AF - 评测集构造与Judge提示词模板库', link: '/附录/附录AF_评测集构造与Judge提示词模板库' },
        ]},
        { text: '平台与评测 AG-AL', collapsed: true, items: [
          { text: 'AG - Human-in-the-Loop速查手册', link: '/附录/附录AG_Human-in-the-Loop速查手册' },
          { text: 'AH - HITL代码模板与审批提示词库', link: '/附录/附录AH_HITL代码模板与审批提示词库' },
          { text: 'AI - LangGraph Platform速查手册', link: '/附录/附录AI_LangGraph Platform速查手册' },
          { text: 'AJ - LangGraph Platform部署配置模板库', link: '/附录/附录AJ_LangGraph Platform部署配置模板库' },
          { text: 'AK - LangSmith速查手册', link: '/附录/附录AK_LangSmith速查手册' },
          { text: 'AL - LangSmith追踪与实验代码模板库', link: '/附录/附录AL_LangSmith追踪与实验代码模板库' },
        ]},
        { text: '行业与模式 AM-AP', collapsed: true, items: [
          { text: 'AM - 垂直行业Agent项目速查手册', link: '/附录/附录AM_垂直行业Agent项目速查手册' },
          { text: 'AN - 垂直行业Agent代码模板库', link: '/附录/附录AN_垂直行业Agent代码模板库' },
          { text: 'AO - Agent设计模式速查手册', link: '/附录/附录AO_Agent设计模式速查手册' },
          { text: 'AP - Agent设计模式代码模板库', link: '/附录/附录AP_Agent设计模式代码模板库' },
        ]},
        { text: '论文与安全 AQ-AT', collapsed: true, items: [
          { text: 'AQ - AI Agent论文阅读指南与必读清单', link: '/附录/附录AQ_AI_Agent论文阅读指南与必读清单' },
          { text: 'AR - 论文复现代码模板库', link: '/附录/附录AR_论文复现代码模板库' },
          { text: 'AS - LLM安全检查清单与防御速查手册', link: '/附录/附录AS_LLM安全检查清单与防御速查手册' },
          { text: 'AT - 安全攻防代码模板库', link: '/附录/附录AT_安全攻防代码模板库' },
        ]},
        { text: '多模态 AU-AV', collapsed: true, items: [
          { text: 'AU - 多模态开发速查手册与模型选型指南', link: '/附录/附录AU_多模态开发速查手册与模型选型指南' },
          { text: 'AV - 多模态代码模板库', link: '/附录/附录AV_多模态代码模板库' },
        ]},
        { text: '编排与多Agent BA-BD', collapsed: true, items: [
          { text: 'BA - 高级编排与HITL速查手册', link: '/附录/附录BA_高级编排与HITL速查手册' },
          { text: 'BB - 编排与批处理代码模板库', link: '/附录/附录BB_编排与批处理代码模板库' },
          { text: 'BC - 多Agent系统速查手册', link: '/附录/附录BC_多Agent系统速查手册' },
          { text: 'BD - 多Agent编排代码模板库', link: '/附录/附录BD_多Agent编排代码模板库' },
        ]},
      ],

      '/课程/': [
        {
          text: '学习课程',
          collapsed: false,
          items: [
            { text: '00 - 课程总览与学习路径', link: '/课程/00-课程总览与学习路径' },
            { text: '01 - 前置知识准备', link: '/课程/01-前置知识准备' },
            { text: '02 - LangChain 入门', link: '/课程/02-LangChain入门-初识框架' },
            { text: '03 - 核心概念 Models-Prompts-Parsers', link: '/课程/03-核心概念-Models-Prompts-Parsers' },
            { text: '04 - Memory 与对话管理', link: '/课程/04-Memory与对话管理' },
            { text: '05 - Chains 链式调用', link: '/课程/05-Chains-链式调用' },
            { text: '06 - Agents 与 Tools', link: '/课程/06-Agents与Tools-智能代理' },
            { text: '07 - RAG 检索增强生成', link: '/课程/07-RAG检索增强生成' },
            { text: '08 - LangChain 进阶与最佳实践', link: '/课程/08-LangChain进阶与最佳实践' },
            { text: '09 - LangGraph 入门', link: '/课程/09-LangGraph入门-图式编排' },
            { text: '10 - LangGraph 核心概念', link: '/课程/10-LangGraph核心概念-State-Nodes-Edges' },
            { text: '11 - 复杂工作流与多 Agent', link: '/课程/11-构建复杂工作流与多Agent系统' },
            { text: '12 - 实战项目从零到一', link: '/课程/12-实战项目-从零到一' },
          ]
        }
      ],

      '/知识库/': [
        {
          text: '基础参考 (01-13)',
          collapsed: true,
          items: [
            { text: '01 - 技术术语表', link: '/知识库/01-技术术语表' },
            { text: '02 - LangChain 架构详解', link: '/知识库/02-LangChain架构详解' },
            { text: '03 - LangGraph 架构详解', link: '/知识库/03-LangGraph架构详解' },
            { text: '04 - API 参考与速查', link: '/知识库/04-API参考与速查手册' },
            { text: '05 - 代码示例集', link: '/知识库/05-代码示例集' },
            { text: '06 - 环境配置指南', link: '/知识库/06-环境配置指南' },
            { text: '07 - 常见问题与排错', link: '/知识库/07-常见问题与排错指南' },
            { text: '08 - 版本演进与生态', link: '/知识库/08-版本演进与生态' },
            { text: '09 - Prompt 工程实战', link: '/知识库/09-Prompt工程实战指南' },
            { text: '10 - 安全与合规', link: '/知识库/10-安全与合规指南' },
            { text: '11 - 评估与测试', link: '/知识库/11-LLM应用评估与测试' },
            { text: '12 - 向量数据库对比', link: '/知识库/12-向量数据库深度对比' },
            { text: '13 - 流式输出与异步', link: '/知识库/13-流式输出与异步编程专题' },
          ]
        },
        {
          text: '前沿技术指南 (427+)',
          collapsed: true,
          items: [
            { text: '427 - MCP 协议与工具集成', link: '/知识库/427-MCP协议与LangChain工具集成指南' },
            { text: '428 - 推理模型与 Agent', link: '/知识库/428-推理模型与Agent集成指南' },
            { text: '429 - 可恢复性与容错', link: '/知识库/429-Agent可恢复性与容错编排指南' },
            { text: '430 - Agentic RAG', link: '/知识库/430-Agentic RAG与自适应检索决策指南' },
            { text: '431 - 长上下文与 RAG', link: '/知识库/431-长上下文模型与RAG策略权衡指南' },
            { text: '432 - Computer Use', link: '/知识库/432-Computer Use与浏览器自动化Agent指南' },
            { text: '433 - Realtime API 语音', link: '/知识库/433-OpenAI Realtime API与语音Agent指南' },
            { text: '434 - 自托管 LLM', link: '/知识库/434-自托管LLM与本地推理部署指南' },
            { text: '435 - 评测工具链', link: '/知识库/435-LLM评测工具链集成指南' },
            { text: '436 - AI 编程 Agent', link: '/知识库/436-AI编程Agent与代码自动化指南' },
            { text: '437 - OpenAI Agents SDK', link: '/知识库/437-OpenAI Agents SDK与多Agent框架指南' },
            { text: '438 - NeMo Guardrails', link: '/知识库/438-NeMo Guardrails与Agent护栏系统指南' },
            { text: '439 - PEFT 微调与 DPO', link: '/知识库/439-PEFT微调与DPO对齐实践指南' },
            { text: '440 - 前端与聊天 UI', link: '/知识库/440-Agent前端与聊天UI构建指南' },
            { text: '441 - LangGraph Platform', link: '/知识库/441-LangGraph Platform部署与生产化指南' },
            { text: '442 - 身份认证与授权', link: '/知识库/442-Agent身份认证与授权体系指南' },
            { text: '443 - 多模态文档 OCR', link: '/知识库/443-多模态文档智能与OCR-Agent指南' },
            { text: '444 - 可解释性 XAI', link: '/知识库/444-Agent可解释性与XAI指南' },
            { text: '445 - 调试与可观测', link: '/知识库/445-Agent调试与可观测工具链指南' },
            { text: '446 - 记忆架构', link: '/知识库/446-Agent记忆架构与长期记忆系统指南' },
          ]
        },
        {
          text: '安全合规与伦理 (447-501)',
          collapsed: true,
          items: [
            { text: '447 - AI 伦理与偏见', link: '/知识库/447-AI伦理与偏见检测指南' },
            { text: '448 - 红队测试与攻防', link: '/知识库/448-Agent红队测试与对抗攻防深度指南' },
            { text: '449 - 隐私计算与联邦学习', link: '/知识库/449-隐私计算与联邦学习指南' },
            { text: '450 - 经济模型与激励', link: '/知识库/450-Agent经济模型与激励机制指南' },
            { text: '451 - 合规与法律框架', link: '/知识库/451-LLM应用合规与法律框架指南' },
            { text: '477 - 数据安全与加密', link: '/知识库/477-Agent数据安全与加密体系指南' },
            { text: '490 - 安全审计与合规', link: '/知识库/490-Agent安全审计与合规自动化指南' },
            { text: '500 - 越狱防护与注入', link: '/知识库/500-Agent越狱防护与提示注入防御深度指南' },
            { text: '501 - 数据保护与隐私', link: '/知识库/501-Agent数据保护与隐私合规深度指南' },
            { text: '561 - 红队工具链', link: '/知识库/561-Agent安全攻防实战与红队工具链指南' },
            { text: '576 - 伦理治理与负责任AI', link: '/知识库/576-Agent伦理治理与负责任AI体系指南' },
          ]
        },
        {
          text: '运维与部署 (478-511)',
          collapsed: true,
          items: [
            { text: '478 - AIOps 智能运维', link: '/知识库/478-AIOps与智能运维指南' },
            { text: '479 - 自动扩缩容', link: '/知识库/479-Agent自动扩缩容与弹性指南' },
            { text: '480 - 日志管理与审计', link: '/知识库/480-Agent日志管理与审计追溯指南' },
            { text: '481 - 变更管理与发布', link: '/知识库/481-Agent变更管理与发布流程指南' },
            { text: '482 - API 设计与 OpenAPI', link: '/知识库/482-Agent API设计与OpenAPI规范指南' },
            { text: '484 - 跨平台与多端', link: '/知识库/484-Agent跨平台与多端部署指南' },
            { text: '485 - 调度与 Cron', link: '/知识库/485-Agent调度与定时任务Cron指南' },
            { text: '486 - Webhook 与通知', link: '/知识库/486-Agent Webhook与事件驱动通知指南' },
            { text: '487 - 最佳实践与反模式', link: '/知识库/487-Agent最佳实践与反模式深度指南' },
            { text: '488 - 环境管理与配置', link: '/知识库/488-Agent环境管理与配置即代码指南' },
            { text: '489 - 容器化与 K8s', link: '/知识库/489-Agent容器化与K8s生产部署指南' },
            { text: '490 - 版本兼容与升级', link: '/知识库/490-Agent版本兼容与平滑升级指南' },
            { text: '491 - 冷启动与预热', link: '/知识库/491-Agent冷启动优化与预热策略指南' },
            { text: '492 - 异地多活与灾备', link: '/知识库/492-Agent异地多活与灾难恢复深度指南' },
            { text: '502 - 可观测性三支柱', link: '/知识库/502-Agent可观测性三支柱整合指南' },
            { text: '503 - SRE 与 On-Call', link: '/知识库/503-Agent SRE与On-Call事件管理指南' },
            { text: '504 - DevOps 与 CI/CD', link: '/知识库/504-Agent DevOps与CI-CD流水线工程化指南' },
            { text: '505 - 云原生与 Serverless', link: '/知识库/505-Agent云原生与Serverless部署指南' },
            { text: '506 - 微服务与服务网格', link: '/知识库/506-Agent微服务拆分与服务网格指南' },
            { text: '507 - 错误处理与恢复', link: '/知识库/507-Agent错误处理与异常恢复工程化指南' },
            { text: '509 - 优雅关闭与排空', link: '/知识库/509-Agent优雅关闭与排空深度指南' },
            { text: '510 - 配置热更新', link: '/知识库/510-Agent配置热更新与动态配置中心指南' },
            { text: '511 - 回滚与版本管理', link: '/知识库/511-Agent回滚与版本管理工程化指南' },
          ]
        },
        {
          text: '工程深度 (512-531)',
          collapsed: true,
          items: [
            { text: '512 - 对话状态机', link: '/知识库/512-Agent对话状态机与槽位填充深度指南' },
            { text: '513 - 推理链优化', link: '/知识库/513-Agent推理链优化与思维链工程化指南' },
            { text: '514 - 工具编排', link: '/知识库/514-Agent工具编排与动态工具链指南' },
            { text: '515 - 情景与语义记忆', link: '/知识库/515-Agent情景记忆与语义记忆深度指南' },
            { text: '516 - 踩坑实录', link: '/知识库/516-Agent踩坑实录与生产事故案例分析指南' },
            { text: '517 - 数据分析可视化', link: '/知识库/517-Agent数据分析与可视化自动化指南' },
            { text: '518 - 代码生成与审查', link: '/知识库/518-Agent代码生成与代码审查深度指南' },
            { text: '519 - 多语言翻译', link: '/知识库/519-Agent多语言翻译与国际化指南' },
            { text: '520 - 搜索增强', link: '/知识库/520-Agent搜索增强与网页信息提取指南' },
            { text: '521 - 内容创作', link: '/知识库/521-Agent内容创作与写作辅助深度指南' },
          ]
        },
        {
          text: '行业应用 (522-556)',
          collapsed: true,
          items: [
            { text: '522 - 教育应用', link: '/知识库/522-Agent教育应用与智能学习辅导指南' },
            { text: '523 - 医疗辅助', link: '/知识库/523-Agent医疗辅助与诊断支持指南' },
            { text: '524 - 金融风控', link: '/知识库/524-Agent金融风控与智能投顾指南' },
            { text: '525 - 法律辅助', link: '/知识库/525-Agent法律辅助与合同审查指南' },
            { text: '526 - 客服自动化', link: '/知识库/526-Agent客服自动化与智能对话指南' },
            { text: '527 - 智能制造', link: '/知识库/527-Agent智能制造与工业互联网指南' },
            { text: '528 - 供应链优化', link: '/知识库/528-Agent供应链优化与物流管理指南' },
            { text: '529 - 能源管理', link: '/知识库/529-Agent能源管理与电力调度指南' },
            { text: '530 - 人力资源', link: '/知识库/530-Agent人力资源与智能招聘指南' },
            { text: '531 - 税务申报', link: '/知识库/531-Agent税务申报与智能审计指南' },
            { text: '532 - 智慧政务', link: '/知识库/532-Agent智慧政务与公共服务指南' },
            { text: '533 - 农业智能化', link: '/知识库/533-Agent农业智能化与精准种植指南' },
            { text: '534 - 智慧交通', link: '/知识库/534-Agent智慧交通与城市管理指南' },
            { text: '535 - 零售电商', link: '/知识库/535-Agent零售电商与智能营销指南' },
            { text: '536 - 心理咨询', link: '/知识库/536-Agent心理咨询与心理健康服务指南' },
            { text: '537 - 旅游规划', link: '/知识库/537-Agent旅游规划与智能出行指南' },
            { text: '538 - 保险理赔', link: '/知识库/538-Agent保险理赔与智能核保指南' },
            { text: '539 - 专利分析', link: '/知识库/539-Agent专利分析与知识产权管理指南' },
            { text: '540 - 智能建筑', link: '/知识库/540-Agent智能建筑与物业管理指南' },
            { text: '541 - 医药研发', link: '/知识库/541-Agent医药研发与临床试验指南' },
            { text: '542 - 环保监测', link: '/知识库/542-Agent环保监测与碳排放管理指南' },
            { text: '543 - 智能汽车', link: '/知识库/543-Agent智能汽车与自动驾驶辅助指南' },
            { text: '544 - 食品安全', link: '/知识库/544-Agent食品安全与质量追溯指南' },
            { text: '545 - 新闻媒体', link: '/知识库/545-Agent新闻媒体与内容采编指南' },
            { text: '546 - 城市规划', link: '/知识库/546-Agent城市规划与智慧社区指南' },
            { text: '547 - 半导体制造', link: '/知识库/547-Agent半导体制造与良率优化指南' },
            { text: '548 - 影视制作', link: '/知识库/548-Agent影视制作与内容创作指南' },
            { text: '549 - 气象预报', link: '/知识库/549-Agent气象预报与灾害预警指南' },
            { text: '550 - 房地产估值', link: '/知识库/550-Agent房地产智能估值与交易指南' },
            { text: '551 - 图书馆管理', link: '/知识库/551-Agent图书馆与智能知识管理指南' },
            { text: '552 - 游戏开发', link: '/知识库/552-Agent游戏开发与智能NPC指南' },
            { text: '553 - 体育分析', link: '/知识库/553-Agent体育分析与赛事辅助指南' },
            { text: '554 - 化工安全', link: '/知识库/554-Agent化工生产安全与工艺优化指南' },
            { text: '555 - 海洋海事', link: '/知识库/555-Agent海洋探索与海事管理指南' },
            { text: '556 - 会展管理', link: '/知识库/556-Agent会展活动管理与智能场馆指南' },
          ]
        },
        {
          text: '前沿探索 (557-591)',
          collapsed: true,
          items: [
            { text: '557 - 多模态融合', link: '/知识库/557-Agent多模态融合与跨模态推理深度指南' },
            { text: '558 - 知识蒸馏', link: '/知识库/558-Agent知识蒸馏与模型压缩实践指南' },
            { text: '559 - 联邦学习', link: '/知识库/559-Agent联邦学习与隐私保护深度指南' },
            { text: '560 - 自进化闭环', link: '/知识库/560-Agent自进化与持续学习闭环指南' },
            { text: '562 - 边缘计算', link: '/知识库/562-Agent边缘计算与端侧部署深度指南' },
            { text: '563 - 量子计算融合', link: '/知识库/563-Agent量子计算融合与未来展望指南' },
            { text: '564 - 区块链应用', link: '/知识库/564-Agent区块链与去中心化应用指南' },
            { text: '565 - 数字人与元宇宙', link: '/知识库/565-Agent数字人虚拟助手与元宇宙指南' },
            { text: '566 - 知识图谱推理', link: '/知识库/566-Agent知识图谱推理与因果推断指南' },
            { text: '567 - 知识管理与搜索', link: '/知识库/567-Agent知识管理与企业搜索深度指南' },
            { text: '568 - 自动化测试', link: '/知识库/568-Agent自动化测试与质量保障体系指南' },
            { text: '569 - 数据治理', link: '/知识库/569-Agent数据治理与数据质量管理指南' },
            { text: '570 - 实时决策', link: '/知识库/570-Agent实时决策与流式处理指南' },
            { text: '571 - 对话体验设计', link: '/知识库/571-Agent自然语言交互与对话体验设计指南' },
            { text: '572 - 运筹优化', link: '/知识库/572-Agent智能决策与运筹优化指南' },
            { text: '573 - 自然语言编程', link: '/知识库/573-Agent自然语言编程与代码即指令指南' },
            { text: '574 - 博弈论与机制设计', link: '/知识库/574-Agent多Agent博弈论与机制设计深度指南' },
            { text: '575 - 认知架构', link: '/知识库/575-Agent认知架构与思维模型指南' },
            { text: '577 - 信任与声誉', link: '/知识库/577-Agent信任与声誉系统指南' },
            { text: '578 - 委托代理', link: '/知识库/578-Agent委托代理与权限委派指南' },
            { text: '579 - 多轮谈判', link: '/知识库/579-Agent多轮谈判与协商协议指南' },
            { text: '580 - 任务分解', link: '/知识库/580-Agent任务分解与分布式执行指南' },
            { text: '581 - 知识更新', link: '/知识库/581-Agent知识更新与增量学习指南' },
            { text: '582 - 知识表示', link: '/知识库/582-Agent知识表示与本体建模指南' },
            { text: '583 - 语义理解', link: '/知识库/583-Agent语义理解与意图深层解析指南' },
            { text: '584 - 自适应推理', link: '/知识库/584-Agent自适应推理与动态策略选择指南' },
            { text: '585 - 情感计算', link: '/知识库/585-Agent多模态情感计算与共情能力指南' },
            { text: '586 - 群体涌现', link: '/知识库/586-Agent群体涌现行为与复杂性管理指南' },
            { text: '587 - Prompt 范式', link: '/知识库/587-Agent提示工程高级模式与范式指南' },
            { text: '588 - 向量库调优', link: '/知识库/588-Agent向量数据库选型与性能调优深度指南' },
            { text: '589 - 流式架构', link: '/知识库/589-Agent流式架构与实时通信工程化指南' },
            { text: '591 - CI/CD 流水线', link: '/知识库/591-Agent持续集成与自动化部署流水线指南' },
          ]
        },
      ],

      '/图解/': [
        {
          text: '基础图解 (00-12)',
          collapsed: false,
          items: [
            { text: '00 - 学习路线全景图', link: '/图解/00-学习路线全景图' },
            { text: '01 - LangChain 生态架构', link: '/图解/01-LangChain生态架构图解' },
            { text: '02 - LCEL 数据流', link: '/图解/02-LCEL数据流图解' },
            { text: '03 - RAG 全流程', link: '/图解/03-RAG全流程图解' },
            { text: '04 - Agent 工作原理', link: '/图解/04-Agent工作原理图解' },
            { text: '05 - Memory 机制', link: '/图解/05-Memory机制图解' },
            { text: '06 - LangGraph 图结构', link: '/图解/06-LangGraph图结构图解' },
            { text: '07 - 多 Agent 架构', link: '/图解/07-多Agent架构图解' },
          ]
        },
        {
          text: '前沿图解 (397+)',
          collapsed: true,
          items: [
            { text: '397 - MCP 协议', link: '/图解/397-MCP协议与LangChain工具集成图解' },
            { text: '398 - 推理模型', link: '/图解/398-推理模型与Agent集成图解' },
            { text: '407 - Agents SDK', link: '/图解/407-OpenAI Agents SDK与多Agent框架图解' },
            { text: '432 - Agent 设计模式', link: '/图解/432-Agent设计模式与参考架构图解' },
            { text: '457 - 最佳实践与反模式', link: '/图解/457-Agent最佳实践与反模式深度图解' },
            { text: '486 - 踩坑实录', link: '/图解/486-Agent踩坑实录与生产事故案例分析图解' },
            { text: '532 - 边缘计算', link: '/图解/532-Agent边缘计算与端侧部署深度图解' },
            { text: '536 - 知识图谱推理', link: '/图解/536-Agent知识图谱推理与因果推断图解' },
            { text: '557 - Prompt 范式', link: '/图解/557-Agent提示工程高级模式与范式图解' },
            { text: '561 - CI/CD 流水线', link: '/图解/561-Agent持续集成与自动化部署流水线图解' },
          ]
        },
      ],

      '/实战案例库/': [
        {
          text: '基础实战',
          collapsed: false,
          items: [
            { text: '00 - 案例库导读', link: '/实战案例库/00-案例库导读' },
            { text: '01 - 智能客服机器人', link: '/实战案例库/01-智能客服机器人' },
            { text: '02 - 多文档 RAG 问答', link: '/实战案例库/02-多文档RAG问答系统' },
            { text: '03 - 代码审查助手', link: '/实战案例库/03-代码审查助手' },
            { text: '04 - 数据分析对话助手', link: '/实战案例库/04-数据分析对话助手' },
            { text: '05 - 多模态文档助手', link: '/实战案例库/05-多模态文档助手' },
            { text: '06 - SQL 数据分析 Agent', link: '/实战案例库/06-SQL数据分析Agent' },
          ]
        },
        {
          text: '进阶实战',
          collapsed: false,
          items: [
            { text: '07 - 实战索引', link: '/实战案例库/07-实战索引与学习路径串联' },
            { text: '08 - Web 搜索 Agent', link: '/实战案例库/08-Web搜索研究Agent' },
            { text: '09 - 自动化工作流', link: '/实战案例库/09-自动化工作流Agent实战' },
            { text: '10 - 进阶 RAG 问答', link: '/实战案例库/10-进阶RAG问答系统实战' },
            { text: '11 - 多 Agent 协作', link: '/实战案例库/11-多Agent协作研究系统' },
            { text: '12 - 数据科学分析', link: '/实战案例库/12-数据科学分析Agent实战' },
          ]
        },
        {
          text: '行业实战精选',
          collapsed: true,
          items: [
            { text: '48 - 智能酒店管理', link: '/实战案例库/48-智能酒店管理Agent实战' },
            { text: '56 - 智能海关通关', link: '/实战案例库/56-智能海关通关Agent实战' },
            { text: '68 - 智能税务申报', link: '/实战案例库/68-智能税务申报Agent实战' },
            { text: '71 - 智能投顾协商', link: '/实战案例库/71-智能投顾多Agent协商实战' },
          ]
        },
      ],

      '/学习评估/': [
        {
          text: '学习评估',
          collapsed: false,
          items: [
            { text: '01 - 里程碑与进度跟踪', link: '/学习评估/01-学习里程碑与进度跟踪' },
            { text: '02 - 题库与面试准备', link: '/学习评估/02-知识检验题库与面试准备' },
            { text: '03 - 速查卡', link: '/学习评估/03-速查卡' },
            { text: '04 - 学习行动计划', link: '/学习评估/04-学习行动计划' },
          ]
        }
      ],
    },

    outline: { level: 2, label: '本页目录' },
    docFooter: { prev: '上一页', next: '下一页' },
    darkModeSwitchLabel: '主题',
    sidebarMenuLabel: '菜单',
    returnToTopLabel: '回到顶部',
    lastUpdatedText: '最后更新',
  },

  mermaid: { theme: 'default' },
  markdown: { lineNumbers: true },
  srcDir: '.',
  srcExclude: ['**/README.md', 'node_modules/**', 'copy-docs.sh', 'copy_new_docs.py', 'gen_sidebar.py', 'gen_ref_app.py'],
  ignoreDeadLinks: true,
}))
